### ISSUE TITLE
Getting "private method `load' called for nil:NilClass" when deploying with capistrano-confirm

### ISSUE THREAD

**Issue by lassebunk** [jinzhu/capistrano-confirm#2]
Hi :)

This is a really nice gem!
However, I get the following error when using it to deploy with Capistrano:

```
private method `load' called for nil:NilClass
/usr/lib/ruby/gems/1.8/gems/capistrano-confirm-0.0.3/lib/capistrano/confirm.rb:5
```

Hope you can help – I'd really like to use your gem!

Best regards,
/Lasse Bunk

**Comment by jinzhu** [comment]
Hi 

   Have you tried with the latest release v0.0.4 (released today) and latest capistrano (2.12.0)?

   Seems it works well for me. could you confirm this? Thanks.

**Comment by lassebunk** [comment]
It works! – Thanks so much :-)

Thanks for making this gem – it's really a great feature to have when you deploy to multiple environments :-)

A small, small typo is that when you type a wrong answer, it says "STOPING..." – this should be "STOPPING..." :-)

Thanks again :-)

/Lasse

**Comment by jinzhu** [comment]
Oh.... thanks to point it out. fixed!

**Comment by lassebunk** [comment]
Hi Jinzhu!

It works perfectly – thanks!

/Lasse

2012/6/25 Jinzhu <
reply@reply.github.com
